### ISSUE TITLE
Button background colors are only declared for dark mode

### ISSUE THREAD

**Issue by ja231c** [Starfield-Community-Patch/Website#12]
The buttons on the site are only visible if dark mode is enabled, nothing else changes on the website between the two modes.
Originally I reported this here, [https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/73](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/73)
Light mode (Microsoft Edge)
<img width="766" alt="edge_light" src="https://github.com/Starfield-Community-Patch/Website/assets/68137237/c058f7a1-7b47-4519-8f5d-efa342111bc6">
Dark mode (Microsoft Edge)
<img width="746" alt="edge_dark" src="https://github.com/Starfield-Community-Patch/Website/assets/68137237/21e0c655-c4c3-4482-a60b-4d7967c4eceb">

Same thing in Firefox (and probably all other browsers), screenshots from Edge since in Edge it's more visible which mode is enabled.

**Comment by Pickysaurus** [comment]
This should be fixed. I believe it was a problem only for users who used Light Mode on their devices.
