### ISSUE TITLE
Report form does not appear

### ISSUE THREAD

**Issue by Tovrin** [Starfield-Community-Patch/Website#13]
The report form does not appear.  I just get the Vasco image and that's all.  I am logged in through Nexus.

**Comment by Tovrin** [comment]
The only error I can see on the console is a warning: "report:1 The resource https://www.starfieldpatch.dev/_next/static/css/feec92941f12186e.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate as value and it is preloaded intentionally."

**Comment by Tovrin** [comment]
Ok .... it appears that the buttons are hidden, but can be clicked on.

**Comment by Pickysaurus** [comment]
This should be fixed. I believe it was a problem only for users who used Light Mode on their devices.
