### ISSUE TITLE
Main content overflowing

### ISSUE THREAD

**Issue by tannivra** [Starfield-Community-Patch/Website#16]
The `.gap-1` class on the main div is causing the body to overflow resulting in a horizontal scrollbar. I wanted to open a pull request but I wanted to make sure it's not just me who's facing this issue. 

I am on a laptop with 2560x1600 resolution. 

![image](https://github.com/Starfield-Community-Patch/Website/assets/66114591/571c070c-f677-44d3-b1e3-f5141f37faf9)
![image](https://github.com/Starfield-Community-Patch/Website/assets/66114591/b0895e92-126f-45c0-9588-5f9f72eec70c)

**Comment by Pickysaurus** [comment]
I'd been meaning to look into this. Thanks for doing the legwork!
