### ISSUE TITLE
Missing metadata from report page.

### ISSUE THREAD

**Issue by eivl** [Starfield-Community-Patch/Website#4]
From discord:

![image](https://github.com/Starfield-Community-Patch/Website/assets/132364/e2aaf471-f34e-4baa-bef3-f145d186c969)

Im assuming a lot here since I cannot find the issue in question or the relevant fix to : https://github.com/Starfield-Community-Patch/Website/blob/df2cda0b35e4268b890e4a4808076960e98b4130/src/app/report/page.tsx#L8C1-L11C1

Compared to the main `page.tsx` that gives this output on discord embeds.

![image](https://github.com/Starfield-Community-Patch/Website/assets/132364/578f09f1-19f9-4ad2-a51a-a4f57b9e4ac2)

with `report/page.tsx` 

![image](https://github.com/Starfield-Community-Patch/Website/assets/132364/643367b6-1d3d-4269-bb2f-887edd1e6630)

Adding more metadata to the page should fix this.

I can make the changes if you inform me of what metadata is wanted. 

example:
```TS
export const metadata: Metadata = {
  title: 'Report an Issue - Starfield Community Patch',
  description: 'The home of the Starfield Community Patch project. Remember, the Community Patch is only intended to fix bugs and errors in the base game.',
}
```

Im also assuming that this would fix the issue as I mirror the main page.tsx metadata. I can still fix it, test it and create a PR of its needed.

**Comment by Pickysaurus** [comment]
Merged https://github.com/Starfield-Community-Patch/Website/pull/7
