### ISSUE TITLE
Find Game Version button does nothing on issue creation form

### ISSUE THREAD

**Issue by skyler3d** [Starfield-Community-Patch/Website#9]
Under **Game Version** where it says "VASCO says: You can learn how to find your game version here." The link does nothing and has an empty anchor tag on the page [https://www.starfieldpatch.dev/report](https://www.starfieldpatch.dev/report). If anyone knows what the link should be, I can get it updated.

![image](https://github.com/Starfield-Community-Patch/Website/assets/212836/1fe4d45e-9ecf-4c8b-acfb-31babe980ea7)

**Comment by Pickysaurus** [comment]
Fixed in https://github.com/Starfield-Community-Patch/Website/commits/master
